### ISSUE TITLE
Answer general questions which are not in PDF ?

### ISSUE THREAD

**Issue by alperinugur** [gabacode/chatPDF#10]
when asked for 

"Who is the first president of USA", 

it answers as: 
"The context information provided does not mention anything about the first president of United States..."

I think there is a tweak to use llm model when the answer is not in the context.

Anyone knows?

**Comment by gabacode** [comment]
You can try using a [PromptTemplate](https://python.langchain.com/docs/modules/model_io/prompts/prompt_templates/) and add a text instruction like "If the question is not related to the context, reply in a way that..." and describe how you'd like the reply to be.

**Comment by alperinugur** [comment]
> You can try using a [PromptTemplate](https://python.langchain.com/docs/modules/model_io/prompts/prompt_templates/) and add a text instruction like "If the question is not related to the context, reply in a way that..." and describe how you'd like the reply to be.

I changed the response mode from 'compact' to 'tree_summarize'  in line 54. worked fine for me .

thanks for the answer!

check my AGI_startup. your code helped a lot in that..

link is here:  [https://github.com/alperinugur/AGI_Startup](https://github.com/alperinugur/AGI_Startup)

**thanks!!**

**Comment by gabacode** [comment]
Thanks, I'm glad to help. Closing.
